# Generated by Django 2.2 on 2023-05-23 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URLMapping',
        ),
    ]
